version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    command: "python /code/manage.py collectstatic && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
